### PR TITLE
Create 20190723-AALE-3rd-Session-Most-Salient-Points .md

### PR DESCRIPTION
**Pull request by CryptosOdysseus**
This AALE 3rd Session Most Salient Points is a digest feedback. It is a recommended warmup reading, before tackling a more comprehensive feedback, to be found in the "Full Takeaway" version coming next. Same methodology to apply in principle for upcoming sessions as well as the 2 previous session feedbacks remaining to be migrated toward Github repositories here.

### CODE REVIEW

**Comment by dazzaji** [comment]
Are you certain you have attributed the people who "directed" this meeting correctly?  Some seemed very quiet and others who were active in preparing materials and presenting are not noted.

**Comment by dazzaji** [comment]
can you please remove spaces from the filename?  There is a space between the name and the extension.  this results in a garbled url.

**Comment by CryptosOdysseus** [comment]
Done and done, new PR with updated version done. The attributions in "AALE-3rd-Session-Salient Points" have been corrected to reflect their (as accurate and fair as can be) original detail in upcoming comprehensive feedback "AALE-3rd-Session-Full-Takeaway". Please kindly advise if further amendments required. Thank you very much for pointing out this important requirement.

**Comment by dazzaji** [comment]
Overtaken by new/different pull requests.

**Pull request closed without merging**
